DROP TABLE IF EXISTS devices;


CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);