-- RTC memory slots
-- Slots 21 - 31 are available
MEMSLOT_LAST_BOOT_TIME = 21
MEMSLOT_LAST_WIFI_TIME = 22
MEMSLOT_NEXT_WIFI_TIME = 23
MEMSLOT_NEXT_VOLTAGE_CHECK_TIME = 24
MEMSLOT_VOLTAGE = 25
MEMSLOT_BOOTS_SINCE_INIT = 26
MEMSLOT_WIFI_INTERVAL = 27
MEMSLOT_SLEEP_INTERVAL = 28
MEMSLOT_VOLTAGE_CHECK_INTERVAL = 29