DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS device_config;
DROP TABLE IF EXISTS device_status;
-- DROP TABLE IF EXISTS readings;


CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mac TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE device_config (
  device_id INTEGER NOT NULL,
  name TEXT,
  calibration_min INTEGER NOT NULL DEFAULT 0,
  calibration_max INTEGER NOT NULL DEFAULT 1000,
  trigger_min INTEGER NOT NULL DEFAULT 0,
  INIT_INTERVAL INTEGER NOT NULL DEFAULT 1,
  SLEEP_DURATION INTEGER NOT NULL DEFAULT 1,
  SLEEP_DELAY INTEGER NOT NULL DEFAULT 10,
  LIGHT INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY(device_id) REFERENCES devices(id)
);


CREATE TABLE device_status (
  device_id INTEGER NOT NULL,
  checkin_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  device_time TIMESTAMP,
  device_next_init TIMESTAMP,
  voltage INTEGER,
  log TEXT,
  FOREIGN KEY(device_id) REFERENCES devices(id)
);


-- CREATE TABLE readings (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   device_id INTEGER NOT NULL,
--   timestamp TIMESTAMP NOT NULL,
--   value INTEGER NOT NULL,
--   offset INTEGER NOT NULL,
--   name TEXT,
--   FOREIGN KEY(device_id) REFERENCES devices(mac)
-- );